name: NicolasMorin
favicon: null
layout_spectrum: 0.2589938573073596
typography_spectrum: 0.49359875242225826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.46618878631852567
  lightness: 0.7639737580902874
  saturation: 0.0038078418001532555
  rhythmicContrast: 0.6401522520463914
purpose: []
